### ISSUE TITLE
VAEAC for Abalone dataset

### ISSUE THREAD

**Issue by aliamini-uq** [LHBO/ShapleyValuesVAEAC#1]
Dear `shapr`,

First of all, congrats on your interesting paper: "[Using Shapley Values and Variational Autoencoders to Explain Predictive Models with Dependent Mixed Features](https://jmlr.org/papers/v23/21-1413.html)". In my opinion, the introduction of `VAEAC ` approach seems promising.

However, to better understand the paper and benefit from reproducible results for end-users, I suggest publicizing the codes related to Abalone dataset, at least. In particular, I am a little bit confused about how to compare different approaches. For example, when I compare the performance of `VAEAC` with `independence` and `empirical` approaches, should I first change the dataset using on-hot encoding for the `independence` and `empirical` approaches? However, I should not change the dataset since VAEAC has an _internal_ mechanism. Am I right?

In addition, other sections of this paper are very interesting, but need more elaboration such as the introduction of "EC3 = EPEv" and "Fig. 10". Thus, It would be great if you share the codes of this outstanding work.

Kind regards,
A

**Comment by LHBO** [comment]
See answer at https://github.com/NorskRegnesentral/shapr/issues/385
